kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-local-claim-1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi