kind: PersistentVolume
apiVersion: v1
metadata:
  name: helm-pv1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/kube"
  storageClassName: local-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: helm-pvc1
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
