kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ops-binding
  namespace: instavote
subjects:
- kind: Group
  name: ops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ops-role
  apiGroup: rbac.authorization.k8s.io
